### ISSUE TITLE
Inner side of sections are empty.Something is wrong with the website

### ISSUE THREAD

**Issue by maydin** [androiddeveloperdays/addwebsite#12]
Inner side of sections are empty.

**Comment by iamkaan** [comment]
also, header background doesn't appear on scroll down

**Comment by ozasadnyy** [comment]
Do you see it now? It can be an issue with Bootstrap cdn

**Comment by maydin** [comment]
Yes i see. thanks

On Mon, Mar 16, 2015 at 11:22 PM, Oleh Zasadnyy notifications@github.com
wrote:

> Do you see it now? It can be issue with Bootstrap cdn
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/androiddeveloperdays/addwebsite/issues/12#issuecomment-81947973
> .

## 

_Murat AYDIN_
_------------------_
Senior Software Engineer & Team Leader at STM http://www.stm.com.tr
Member at GDG Ankara http://www.gdgankara.org

http://tr.linkedin.com/in/maydn [image: Google +]
https://plus.google.com/u/0/103192161215711346911
https://twitter.com/maydintr
Blog   : www.ottodroid.net
