### ISSUE TITLE
Become A Sponsor

### ISSUE THREAD

**Issue by androiddeveloperdays** [androiddeveloperdays/addwebsite#15]
is it possible to put a page similar to here http://www.androiddeveloperday.com/2015/sponsor-olun/
when become a sponsor is clicked

**Comment by ozasadnyy** [comment]
I suppose there should be some form, but I can't see it: http://awesomescreenshot.com/0214okiw5b

**Comment by maydin** [comment]
Then could you put a page that is like
Become a Sponsor

Please contact us by contact@androiddeveloperdays.com

On Fri, Mar 20, 2015 at 9:53 PM, Oleh Zasadnyy notifications@github.com
wrote:

> I suppose there should be some form, but I can't see it:
> http://awesomescreenshot.com/0214okiw5b
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/androiddeveloperdays/addwebsite/issues/15#issuecomment-84123303
> .

## 

_Murat AYDIN_
_------------------_
Senior Software Engineer & Team Leader at STM http://www.stm.com.tr
Member at GDG Ankara http://www.gdgankara.org

http://tr.linkedin.com/in/maydn [image: Google +]
https://plus.google.com/u/0/103192161215711346911
https://twitter.com/maydintr
Blog   : www.ottodroid.net

**Comment by ozasadnyy** [comment]
We can add Google forms on the page.
