### ISSUE TITLE
banners-for-supporters/

### ISSUE THREAD

**Issue by androiddeveloperdays** [androiddeveloperdays/addwebsite#16]
I remember that you put this page but it is not visible

**Comment by ozasadnyy** [comment]
I haven't because I can't see that banners.

**Comment by androiddeveloperdays** [comment]
You cant because of the adblocker. Currently we dont have any other banners. either we should put these banners or we should remove banners for websites page until we design image banners. What do you offer?

**Comment by ozasadnyy** [comment]
I will create a page but remove links from footer.
