### ISSUE TITLE
grunt task for reducing image size

### ISSUE THREAD

**Issue by salimkayabasi** [androiddeveloperdays/addwebsite#25]
Some of images are too much big.
Slow loading will be problem in mobile browsing

Here the examples

![gdgtekirdag](http://www.androiddeveloperdays.com/2015/img/organizers/gdgTekirdag.jpg)
![3ik](http://androiddeveloperday.com/2015/img/associations-foundations-and-firms/3ik.png)
![cyberedges](http://androiddeveloperday.com/2015/img/web-sites-and-blogs/www.cyberedges.com.jpg)
![bau-ieee-sb](http://androiddeveloperday.com/2015/img/communities/bau-ieee-sb.png)

**Comment by androiddeveloperdays** [comment]
does this task reduce all images or can we choose?
Speaker images need to be at least 400x400

**Comment by salimkayabasi** [comment]
I didn't give any task name but knew that there are too much grunt modules for your requirements

**Comment by ozasadnyy** [comment]
But you need to install [ImageMagick](http://www.imagemagick.org/script/binary-releases.php)

**Comment by salimkayabasi** [comment]
u r the king :)
