### ISSUE TITLE
Side Menu or Submenu

### ISSUE THREAD

**Issue by androiddeveloperdays** [androiddeveloperdays/addwebsite#4]
Can we put a side menu to the top page?
Side menu could be similar to http://www.androiddeveloperdays.com/2015/

Or submenu to the top menu. For instance There will be Supporters in the top menu and when you click it, a sub menu will open listing websites and blogs, associations and firms etc..

We need a way to show side menus here: http://www.androiddeveloperdays.com/2015/

**Comment by ozasadnyy** [comment]
I have moved all links from sidebar to footer.
If it's not satisfy you, I can try to add a dropdown menu to navbar.

**Comment by androiddeveloperdays** [comment]
A dropdown menu would be better.
